version: '3.3'

services:
  streamlit:
    build: .
    environment:
      - DB_USER=app
      - DB_PASS=app
      - DB_IP=leanxcaledb-service  # Use service name for Docker network
      - DB_PORT=1529
      - DB_NAME=MOH
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
  leanxcaledb-service:
    image: harbor.gftinnovation.eu/fame/leanxcaledb-fdac-demo:1.9.13
    container_name: leanxcaledb-service
    restart: unless-stopped
    ports:
      - 2181:2181
      - 1529:1529
    environment:
      - KVPEXTERNALIP=leanxcaledb-service!9800
