version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DB_USER=${DB_USER:-app}
      - DB_PASS=${DB_PASS:-app}
      - DB_IP=${DB_IP:-leanxcaledb-service}
      - DB_PORT=${DB_PORT:-1529}
      - DB_NAME=${DB_NAME:-MOH}
    ports:
      - "8000:8000"
    networks:
      - lxs_network

networks:
  lxs_network:
    external: true


