version: '3.3'

services:
  streamlit:
    build: .
    environment:
      - DB_USER=app
      - DB_PASS=app
      - DB_IP=leanxcaledb-service  # Use service name for Docker network
      - DB_PORT=1529
      - DB_NAME=MOH
      - STREAMLIT_SERVER_PORT=8501
    ports:
      - "8501:8501"
    networks:
      - lxs_network

networks:
  lxs_network:
    external: true
